### ISSUE TITLE
[feature] 온보딩페이지 마무리

### ISSUE THREAD

**Issue by seungje1217** [2024-SUMMER-BOOTCAMP-TEAM-A/frontend#13]
## 작업 내용 설명

main페이지의 온보딩 페이지 마무리입니다
## 체크리스트

src/main에 있는 StarField.tsx 페이지 마무리 작업입니다 (각 세션 별 피그마에 있는 구성 요소 추가 예정)
- [ ]

**Comment by kimjusnu** [comment]
.
